stages:
  - build
  - push-backend
  - push-frontend

cache:
  paths:
    - .m2/repository

build:
  stage: build
  tags: [gcp]
  image: maven:3.8.4-openjdk-17
  script:
    - cd manage-my-cloud-backend
    - mvn clean install

backend:
  stage: push-backend
  tags: [gcp]
  image: google/cloud-sdk:alpine
  script:
    - echo $GCP_CLOUD_BUILD_SERVICE_KEY > /tmp/gcloud-service-key.json
    - sudo gcloud auth activate-service-account container-iam@finalyearproject-406016.iam.gserviceaccount.com --key-file /tmp/gcloud-service-key.json
    - sudo gcloud config set project finalyearproject-406016
    - cd manage-my-cloud-backend
    - sudo docker build -t manage-my-cloud-backend .
    - sudo docker tag manage-my-cloud-backend gcr.io/finalyearproject-406016/manage-my-cloud-backend:latest
    - sudo docker push gcr.io/finalyearproject-406016/manage-my-cloud-backend:latest
  when: manual
  after_script: 
    - sudo docker image remove -f manage-my-cloud-backend
    - rm /tmp/gcloud-service-key.json

frontend:
  stage: push-frontend
  tags: [gcp]
  image: google/cloud-sdk:alpine
  script:
    - echo $GCP_CLOUD_BUILD_SERVICE_KEY > /tmp/gcloud-service-key.json
    - sudo gcloud auth activate-service-account container-iam@finalyearproject-406016.iam.gserviceaccount.com --key-file /tmp/gcloud-service-key.json
    - sudo gcloud config set project finalyearproject-406016
    - cd manage-my-cloud-frontend
    - sudo docker build -t manage-my-cloud-frontend .
    - sudo docker tag manage-my-cloud-frontend gcr.io/finalyearproject-406016/manage-my-cloud-frontend:latest
    - sudo docker push gcr.io/finalyearproject-406016/manage-my-cloud-frontend:latest
  when: manual
  after_script: 
    - sudo docker image remove -f manage-my-cloud-frontend
    - rm /tmp/gcloud-service-key.json
