image: maven:3.8.4-openjdk-17

stages:
  - build
  - gcp

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - cd manage-my-cloud-backend
    - mvn clean install
gcp:
  stage: gcp
  image: google/cloud-sdk:alpine
  script:
    - echo $GCP_CLOUD_BUILD_SERVICE_KEY > /tmp/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
    - gcloud config set project finalyearproject-406016
    - docker build -t manage-my-cloud-backend .
    - docker tag manage-my-cloud-backend gcr.io/finalyearproject-406016/manage-my-cloud-backend:latest
    - docker push gcr.io/finalyearproject-406016/manage-my-cloud-frontend:latest
    - docker image remove -f manage-my-cloud-backend
  only:
    - master
  when:
    - manual

after_script:
  - rm /tmp/gcloud-service-key.json
