stages:
  - build
  - gcp

cache:
  paths:
    - .m2/repository

build:
  stage: build
  tags: [gcp]
  image: maven:3.8.4-openjdk-17
  script:
    - cd manage-my-cloud-backend
    - mvn clean install

gcp:
  stage: gcp
  tags: [gcp]
  image: google/cloud-sdk:alpine
  script:
    - echo $GCP_CLOUD_BUILD_SERVICE_KEY > /tmp/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
    - cd manage-my-cloud-backend
    - sudo docker build -t manage-my-cloud-backend .
    - sudo docker tag manage-my-cloud-backend gcr.io/finalyearproject-406016/manage-my-cloud-backend:latest
    - sudo docker push gcr.io/finalyearproject-406016/manage-my-cloud-backend:latest
  when: manual
  after_script: 
    - sudo docker image remove -f manage-my-cloud-backend
    - rm /tmp/gcloud-service-key.json
