version: "3.1"

services:
  manage-my-cloud:
    image: manage-my-cloud:latest
    container_name: manage-my-cloud
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ONEDRIVE_CLIENT_ID= a1418afc-b4bb-4e55-8184-cc77c502f087
      - ONEDRIVE_CLIENT_SECRET= eGS8Q~XW2Tx6FuJW91lP5UHl_WMwhOFYQnX..baB
      - ONEDRIVE_REDIRECT_URI= http://localhost:3000/manage-connections
      - MMC_EMAIL_PASSWORD= xenk pzya jptf xape
      - SPRING_PROFILES_ACTIVE=docker
      - GOOGLE_CREDENTIALS_JSON={"web":{"client_id":"897733650985-l3188hg9ni6cfd61kf9jpkcce5b83omt.apps.googleusercontent.com","project_id":"finalyearproject-406016","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"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","redirect_uris":["https://www.example.org/token"],"javascript_origins":["http://localhost:3000","http://localhost:8080"]%7D%7D
      
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
